# Generated by Django 2.1.2 on 2019-02-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('base', models.CharField(max_length=128)),
                ('lengh', models.CharField(max_length=128)),
                ('tech', models.CharField(max_length=128)),
                ('alc', models.IntegerField(max_length=128)),
                ('taste', models.CharField(max_length=128)),
                ('material1', models.CharField(max_length=128)),
                ('material2', models.CharField(max_length=128)),
                ('contents', models.CharField(max_length=128)),
            ],
        ),
    ]
