# Generated by Django 2.1.2 on 2019-02-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='alc',
            field=models.IntegerField(),
        ),
    ]
