# Generated by Django 2.1.2 on 2019-02-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0002_auto_20190219_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='alc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='contents',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='material1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='material2',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
