# Generated by Django 2.1.2 on 2019-02-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0004_record_cocktail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
