# Generated by Django 2.1.5 on 2019-05-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('base', models.CharField(max_length=128)),
                ('lengh', models.CharField(max_length=128)),
                ('tech', models.CharField(max_length=128)),
                ('alc', models.IntegerField(null=True)),
                ('taste', models.CharField(max_length=128)),
                ('material1', models.CharField(max_length=128, null=True)),
                ('material2', models.CharField(max_length=128, null=True)),
                ('contents', models.CharField(max_length=128, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
